declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.bmp'
declare module '*.tiff'
declare module '*.mp3'
declare module '*.frag'
declare module '*.vert'
declare module '*.glsl'
declare module 'evaluater-vkm'
declare let vkTrack: any;